### ISSUE TITLE
Complete data dictionary documentation for trilogy datasets

### ISSUE THREAD

**Issue by j-hagedorn** [j-hagedorn/trilogy#43]

**Comment by j-hagedorn** [comment]
> What do you mean completing the data dictionary? I lost track of it. Let me know and I can jump on it.

@salmonix, the data dictionary is the [markdown documentation here](https://github.com/j-hagedorn/trilogy/blob/master/docs/data_dictionary.md), which provides definitions of the datasets in the Trilogy, and of each field in each file.

Happy to have you review what I've got there already and propose edits and additions in a new branch.  Would that work for you?

**Comment by salmonix** [comment]
Yo, casting eyes on it.
