### ISSUE TITLE
Resolve non-valid ATU IDs in AFT dataset

### ISSUE THREAD

**Issue by j-hagedorn** [j-hagedorn/trilogy#48]
Pasting your e-mail to track its resolution, @sdaranyi  
"Hi Josh, I started to work with the AFT to exemplify on an existing corpus how things would look if people started using an existing Python workflow in Orange...:
- I am using the aft.csv (21-03-25 in my folder -- pretty old, if the current version has mended the problem to be described below, please ignore this);
- It has atu-Id values well beyond 2400, the upper limit of tale types in the ATU. With not even the list of Discontinued types containing identifiers between 3000-7080, I simply have no idea where Ashliman may have gotten these types from, but chances are that he used something else, not the ATU;
- The column type_identifier contains strings not found in the ATU. No matches whatsoever, so again the question is if Ashliman used an older typology or his own."

**Comment by sdaranyi** [comment]
I have checked itnow  vs the AT, there the last type is No 2411. So those numbers come from elsewhere. But we already noticed something problematic there, cf my file in the Trilogy local folder entitled 'fishy aft ids_ill matches with atu.xlsx' albeit with a much shorter list -- have you got a copy of that? Now I can see that it was discovered while you prepared Fig 1 for JOHD, and we guessed that these must be Christiansen’s tale types (Christiansen, 1992, nowhere a downloadable copy). Bingo: see the aft.xlsx (22-02-27) where in row 1192 it says: "Link to additional Fairy Cup Legends (migratory legends of Christiansen type 6045 and other stories of drinking vessels stolen from or abandoned by fairies)." This will be a good-to-know limitation.

**Comment by j-hagedorn** [comment]
Hey @sdaranyi I looks like this issue is resolved in the master version of the repository.  From your comments above, it seems as though you may be referencing older file versions, which I'd recommend you get rid of.  When I check the current datasets:  
```
atu_df <- read_csv("https://raw.githubusercontent.com/j-hagedorn/trilogy/master/data/atu_df.csv")
aft <- read_csv("https://raw.githubusercontent.com/j-hagedorn/trilogy/master/data/aft.csv")
unmatched <- aft %>% anti_join(atu_df %>% select(atu_id,tale_name), by = "atu_id")
```
Then the number of unmatched IDs between the `aft` and `atu_df` datasets (i.e. `nrow(unmatched)`) = 0.  So, the `aft` in it's published version does not contain those Christiansen references.  I'm marking this issue as closed, but please let me know if you see anything else that looks odd!  I'm grateful to have other eyes on these datasets for quality control.

**Comment by sdaranyi** [comment]
Hi Josh, thanks. I've downloaded both now. The aft.csv upon import in Excel
has extra empty rows from row 1476 onwards, which could be unpleasant for
processing. The atu_df.csv, on the other hand, is littered with question
marks in black rombuses, see below. How can I get rid of them?

[image: image.png]

As soon as time shall permit I'll redo the respective experiments in Orange.

**Comment by sdaranyi** [comment]
Actually something stranger is happening (unless my laptop is making fun of
me). From row/line 1476 in the aft.cv, the atu_ids disappear and some story
is appearing in every second line, stripped of any recognizable cues.

**Comment by j-hagedorn** [comment]
> From row/line 1476 in the aft.cv, the atu_ids disappear and some story is appearing in every second line, stripped of any recognizable cues.

My guess is that this is due to some part of Excel's settings for importing the .csv.  For instance, the commas inside of the text quotes might be causing line returns.  I can look into it and see if there's something I can do with encoding the file.  I reopended the issue.

> The atu_df.csv, on the other hand, is littered with question marks in black rombuses, see below.

I'll flag this as another cleanup step in #42

**Comment by j-hagedorn** [comment]
Reopening this issue due to a few e-mail requests from @sdaranyi , to allow for working with data in Orange.

**Comment by sdaranyi** [comment]
Thanks Josh!

**Comment by j-hagedorn** [comment]
@sdaranyi this issue should be fixed.  I tested it in Excel and it works fine.

**Comment by sdaranyi** [comment]
Confirmed, it works, good sandbox level results. One way to showcase the approach -- build and equip your own castle, bake your own delicious mudcakes. :-) Below attached please find the joint semantic-sentiment space of the AFT for a first try.
![AFT joint space 24-03-06_ACM   kriging](https://github.com/j-hagedorn/trilogy/assets/74593590/052ccbfd-cfac-4e54-854f-fbbe1753ac20)

**Comment by j-hagedorn** [comment]
Cool.  Can you let me know what algorithms/methods you're using in Orange, so that I can test them out using reproducible (code-based) approaches?
